Remove item accounting
versity/scoutfs pull request #10
Opened 2021-01-18 18:13 UTC by agrover

Remove item accounting.

2021-01-19 20:46 UTC, zabbo requested changes
If we're going to do this, let's do it -- I'm cool with either dropping the removal or going the rest of the way.

2021-01-19 20:46 UTC, zabbo commented on kmod/src/scoutfs_trace.h
> +		 int reserved_items,
Oh, if we're removing the item accounting, we're not just removing the arguments to hold and release.  We'd be removing all the accounting in the transactions too.  That's the book keeping to remove :).  So no more reserved/actual fields.

2021-01-21 01:02 UTC, agrover commented
Like this?

Is there more??

2021-01-21 17:57 UTC, zabbo commented
That was it!  There's still refinement to do -- the "reservation" isn't anymore, it's just a per-task count of holders so that nested holds don't block waiting for their caller's hold to release.  We wouldn't need to do that with a full allocated struct, we could just use the task_struct journal_info pointer itself, but we can leave all that for the day when we want to make the transaction holds less expensive.  And we might need it again if we have to do reservations to properly address the premature enospc case over in the metadata allocators.

2021-01-21 17:57 UTC, merged