Don't pass data version to attr_x unless the ioctl means to set it.
versity/scoutfs pull request #183
Opened 2024-09-10 03:28 UTC by aversecat

A small bug in the translation code from setattr_more to attr_x caused setattr to fail if a size zero was passed but no data version was passed.

Add a small test case for this. Without the fix this will produce the following error output ,and nothing with the fix:

  == i_size zero should not require data version to be set
  setattr_more ioctl failed on '/mnt/test.0/test/setattr_more/file': Invalid argument (22)
  scoutfs: setattr failed: Invalid argument (22)

2024-09-10 03:32 UTC, versity-github commented
Build 211 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/211/ git: aac84ebbf57e38f2940b375704810d399a0963c9

2024-09-10 04:09 UTC, versity-github commented
Build 187 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/187/ git: aac84ebbf57e38f2940b375704810d399a0963c9

2024-09-10 16:11 UTC, bendischinger commented on kmod/src/ioctl.c
The comment at line 644 is no longer accurate: "We unconditionally fill the iax attributes from the sm set and let set_attr_x check them."

I'm wondering if it would make more sense to allow setting data_version = 0 if size = 0 at scoutfs/kmod/src/attr_x.c:132 since this seems to be a valid condition.

2024-09-10 22:38 UTC, aversecat commented on kmod/src/ioctl.c
A data version of `0` for a file that is being staged seems weird. Once there's data in it, it can't be zero anymore, data_version will always be `> 0`, right?

2024-09-11 17:34 UTC, bendischinger commented on kmod/src/ioctl.c
These are files that are being restored from a dump.  In the case of restoring an empty file, data version is 0 and size is 0.

2024-09-11 18:54 UTC, aversecat commented
Yes, but, do you actually release content with zero byte lengths? There are
no extents in a zero-byte file.

On Wed, Sep 11, 2024 at 10:34 AM Ben Dischinger ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On kmod/src/ioctl.c
> <https://github.com/versity/scoutfs/pull/183#discussion_r1755220472>:
>
> These are files that are being restored from a dump. In the case of
> restoring an empty file, data version is 0 and size is 0.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/versity/scoutfs/pull/183#discussion_r1755220472>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7C27XFYS2OGZ4R6YH27VXDZWB5MBAVCNFSM6AAAAABN5ZWPO2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOJYGA4TEMBTGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-12 18:34 UTC, bendischinger commented
> Yes, but, do you actually release content with zero byte lengths? There are no extents in a zero-byte file.

We may still make the call, not sure, would expect it to be a no op.

Any rate, I am fine with leaving the change as per Zach's comment in slack.
> So, really, just stop setattr_mroe from asking attr_x_set to change data_version if the setattr_more payload is 0.

2024-09-12 18:34 UTC, bendischinger approved these changes

2024-09-24 19:59 UTC, aversecat commented
retest

2024-09-24 20:36 UTC, versity-github commented
Build 229 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/229/ git: aac84ebbf57e38f2940b375704810d399a0963c9

2024-09-24 20:38 UTC, versity-github commented
Build 205 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/205/ git: aac84ebbf57e38f2940b375704810d399a0963c9

2024-09-24 21:45 UTC, aversecat commented
CI failed on `[  750.874382] scoutfs f.dc3622.r.2ff47d error: error -2 committing log merge: getting merge status item
`

2024-09-27 17:31 UTC, zabbo requested changes
The commit title is correct, but the commit message and test language is misleading.  This has nothing to do with i_size.  It is only about the setattr_more wrapper setting the data_version flag while data_version is 0.  Which the code change correctly does.  Fix the commit summary and test to describe what's going on and we're off to the races.

2024-09-27 23:34 UTC, aversecat commented
I went all out on the wording to try and avoid the all the confusion. Hopefully this is much clearer this way now...

2024-09-28 00:11 UTC, versity-github commented
Build 234 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/234/ git: b45fbe0bbba45691258fe276c406569f9f8c1b8c

2024-09-28 00:12 UTC, versity-github commented
Build 210 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/210/ git: b45fbe0bbba45691258fe276c406569f9f8c1b8c

2024-10-03 18:37 UTC, bendischinger approved these changes

2024-10-03 19:25 UTC, merged