Sparse fix for epel 0.6.4 sparse - redefines
versity/scoutfs pull request #187
Opened 2024-09-19 22:05 UTC by aversecat

We should rely on sparse from epel to do automated sparse checking and not a git tag. But the 0.6.4 build currently fails on sparse/gcc redefines.

This magic Awk from Zach script processes sparse and gcc internal defines and leaves the one intact that sparse doesn't have.

It's wrapped in a simple "atomic" shell test to see if it exists and makes it in a tmp file which renames it into place so that `make -j` properly functions and doesn't cause a midway truncated file.

2024-09-19 22:44 UTC, versity-github commented
Build 198 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/198/ git: fe3183147be11bc494eab9482a4d7f6fead870b0

2024-09-19 22:45 UTC, versity-github commented
Build 222 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/222/ git: fe3183147be11bc494eab9482a4d7f6fead870b0

2024-09-20 17:39 UTC, versity-github commented
Build 200 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/200/ git: fe3183147be11bc494eab9482a4d7f6fead870b0

2024-09-20 17:40 UTC, versity-github commented
Build 224 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/224/ git: fe3183147be11bc494eab9482a4d7f6fead870b0

2024-09-27 18:26 UTC, zabbo requested changes

2024-09-27 18:26 UTC, zabbo commented on utils/sparse.sh
> -# We're trying to use sparse against glibc headers which go wild trying to
Don't remove the comment that describes  why this nonsense is in here.  The text you ended up with should replace the "But not __SIZE_TYPE" as that's all that you're changing, and leave the initial text.

2024-09-27 18:26 UTC, zabbo commented on utils/sparse.sh
> +if [[ ! -f $defines ]]; then
This now never recalculates the defines if the toolchain changes.  Get rid of the test and mv.  Append .$$ to the defines="" file name so each invocation uses its own file.  Then remove it after the sparse invocation.  It'll still have the prefix that'll be removed by make clean if it gets interrupted or crashes.

2024-09-27 20:19 UTC, versity-github commented
Build 209 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/209/ git: 3b8d2eab8ef7066cf0d9cd67c838ba1b03c68773

2024-09-27 20:20 UTC, versity-github commented
Build 233 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/233/ git: 3b8d2eab8ef7066cf0d9cd67c838ba1b03c68773

2024-09-27 21:13 UTC, merged